export interface Order {
    _id:number|undefined,
    userId: string ,
    fname: string,
    lname: string,
    address: string,
    city: string,
    postcode: number,
    email: string,
    contact: string,
    totalPrice: number,
    productName: string,
    productImage?:File,
    productDescription: string,
    productPrice: number
    productColour: string,
    productQuantity: number,
    productCategory: string,
    price: number,
    shipping: number,
    discount: number,
}